version: '3.3'

services:
    haste:
        image: 
        ports:
            - "7777:7777"
        environment:
            - REDIS_HOSTNAME: redis
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:5-alpine
        restart: unless-stopped
