version: '3.3'

services:
    haste:
        build: .
        image: clrxbl/haste
        ports:
            - "7777:7777"
        environment:
            - STORAGE_TYPE=redis
            - STORAGE_HOSTNAME=redis
            - STORAGE_PORT=6379
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:5-alpine
        restart: unless-stopped
